version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.20.1
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PWD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-temporal}
      - POSTGRES_SEEDS=postgres
      - AUTO_SETUP=true
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    depends_on:
      - postgres

  temporal-setup:
    image: temporalio/admin-tools:1.20.1
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      sleep 10 &&
      tctl --namespace order-management namespace register --retention 24h &&
      tctl --namespace payment-management namespace register --retention 24h &&
      tctl --namespace inventory-management namespace register --retention 24h &&
      tctl namespace list
      "
    depends_on:
      - temporal

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-temporal}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  temporal-web:
    image: temporalio/ui:2.20.0
    ports:
      - "8088:8080"
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_ADDRESS=temporal:7233
      - LOG_LEVEL=debug
      - TEMPORAL_DEFAULT_NAMESPACE=order-management
    depends_on:
      - temporal

volumes:
  postgres-data:
  redis-data:
